Remove type ignore
Still need to figure out why I receive this error locally without it:
    error: Untyped decorator makes function "main" untyped  [misc]